name: find_university
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Network Client
  dio: ^5.0.1
  # Internet connection checker
  internet_connection_checker: ^1.0.0+1
  # State management
  flutter_bloc: ^8.1.2
  # Service Locator
  get_it: ^7.2.0
  # Local cache
  shared_preferences: ^2.0.18
  # Value equality
  equatable: ^2.0.5
  # Functional Programming
  dartz: ^0.10.1
  # Navigating Screens
  go_router: ^6.2.0
  # Url Launcher
  url_launcher: ^6.1.10
  



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
